version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir dist
      - echo HAHAHA
      - aws cloudformation package --template-file cfn-templates/main.yml --output-template dist/packaged.yml --s3-bucket test-nested-stack-cfn-iddt --region us-east-1
      - aws cloudformation deploy --template-file dist/packaged.yml --stack-name image-stock-main-stack --region us-east-1 --capabilities CAPABILITY_NAMED_IAM