version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir dist
      - aws cloudformation package --template-file cfn-templates/main.yml --output-template dist/packaged.yml --s3-bucket ${S3_TEMPLATE_BUCKET} --region ${AWS_REGION}
      - aws cloudformation deploy --template-file dist/packaged.yml --stack-name ${MAIN_STACK} --region ${AWS_REGION} --capabilities CAPABILITY_NAMED_IAM