AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  ImageHandlerFuncName:
    Description: Image handler function name
    Type: String
    Default: ResizeImageFunc

  LambdaSrcBucketName:
    Description: Bucket store src code for lambda function
    Type: String
    Default: test-image-stock-lambda-src-bucket

  ImageFormat:
    Description: Image format using to reformat the origin image
    Type: String
    AllowedValues:
      - jpg
      - png
    Default: jpg

  SizeMediumWidth:
    Description: The width of medium size for resizing image
    Type: Number
    Default: 300
  
  SizeSmallWidth:
    Description: The width of small size for resizing image
    Type: Number
    Default: 150

  DestinationBucketName:
    Description: S3 destination bucket name
    Type: String
    Default: test-image-stock-dest-bucket

  ImageTableName:
    Type: String

  ImageHandlerDependenciesLayerName:
    Description: Dependencies layer name for image handler function
    Type: String
    Default: test-image-stock-func-layer

  JobQueueArn:
    Type: String

Resources:
  ImageHandlerFunc:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function get image from s3 and resize
      FunctionName: !Ref ImageHandlerFuncName
      Handler: function/index.handler
      MemorySize: 128
      Role: !GetAtt ImageHandlerFuncRole.Arn
      Runtime: nodejs12.x
      Timeout: 20
      Code:
        S3Bucket: !Ref LambdaSrcBucketName
        S3Key: image-handler/function.zip
      Environment:
        Variables:
          IMAGE_FORMAT: !Ref ImageFormat
          SIZE_MEDIUM_WIDTH: !Ref SizeMediumWidth
          SIZE_SMALL_WIDTH: !Ref SizeSmallWidth
          DESTINATION_BUCKET: !Ref DestinationBucketName
          IMAGE_TABLE_NAME: !Ref ImageTableName
      Layers:
        - !Ref ImageHandlerLib

  ImageHandlerLib:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref ImageHandlerDependenciesLayerName
      Description: Dependencies for the image handler function
      Content:
        S3Bucket: !Ref LambdaSrcBucketName
        S3Key: image-handler/lib.zip
      CompatibleRuntimes:
        - nodejs12.x
  
  # ImageHandlerEventSourceMapping:
  #   Type: AWS::Lambda::EventSourceMapping
  #   DependsOn:
  #     - ImageHandlerFunc
  #   Properties:
  #     BatchSize: 10
  #     Enabled: true
  #     EventSourceArn: !Ref JobQueueArn
  #     FunctionName: !GetAtt ImageHandlerFunc.Arn

  ImageHandlerFuncRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: /
      Policies:
        - 
          PolicyName: logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        -
          PolicyName: allowSQS
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !Ref JobQueueArn
        -
          PolicyName: originBucketGetObject
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: '*'
        -
          PolicyName: AllowPutItemDynamoDB
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - dynamodb:BatchWriteItem
                Resource: arn:aws:dynamodb:*:*:*

Outputs:
  ImageHandlerFuncArn:
    Value: !GetAtt ImageHandlerFunc.Arn